# Set locale
- name: Ensure a locale exists
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items: "{{ server_locales }}"

# install pip3
- name: Install apt packages
  apt:
    name: "{{ apt_packages }}"
    update_cache: yes
    state: present


# install python packages
- name: Install required pip deps
  pip:
    name: "{{ python_packages }}"
    executable: "/usr/local/bin/pip3"